---
title: "Supplementary Information (SI)"
format: 
  pdf:
   number-sections: true
   mathspec: true
   include-in-header: 
      text: '\usepackage{lineno}\linenumbers'
crossref:
  fig-title: Figure S
editor: source
bibliography: references.bib
csl: /Users/dhruvakathuria/Zotero/styles/apa.csl
editor_options: 
  chunk_output_type: console
  markdown:
    canonical: true
---

![Decrease in the root mean squared error between the full model and the reduced model (on the standardized scale) as we add more wavelengths to the full model using step-wise forward selection. The horizontal line at 0 represents the step where adding more wavelengths results in similar predictive accuracy between the full model and submodel according to the cross-validation root mean squared error. The vertical bars represents one standard deviation in cross validation rmse. The number of wavelengths are chosen when the one standard deviation bar intersects the horizontal line.](paper_draft/figures/wavelength_selection_all_covariates.png)

```{r}
#| echo: FALSE
#source("R_codes/Plotting/bivariate_and_marginal_posterior_plots.R")
```

![Posterior distribution for five projected regression parameters and the projected sigma parameter of the reduced model for carotenoid. The regression parameters for wavelengths 1191 nm and 1194 nm are correlated with each other resulting in long univariate posterior parameter intervals of these parameters (Figure 7, Main text)](paper_draft/figures/bivariate_plots_for_Carotenoid_Area.png){#fig-bivariate_posterior_parameter}
